### ISSUE TITLE
Issue when starting driver

### ISSUE THREAD

**Issue by filipDN** [JannesP/AudioMirror#13]
Hello,

I have issue when starting driver. Do you have idea what should I check?

![image](https://user-images.githubusercontent.com/98592429/196473541-a9baf2be-83f2-4642-983d-61ea9480b321.png)

Thanks in advance!

Best regards,
Filip

**Comment by forlayo** [comment]
I think I found your issue..

I suppose you had migrated all calls to "ExAllocatePoolWithTag" as explained [here](https://learn.microsoft.com/en-us/windows-hardware/drivers/kernel/updating-deprecated-exallocatepool-calls). As getting a warning-as-an-error issue.

The thing is that is not as easier as changing the call to ExAllocatePool2 as the usage changes as well, I suppose in special with free.

Instead of doing that if you just go to the vcxproj and change the TreatWarningAsError to false and compile it would work and will not show that bad status.

![image](https://user-images.githubusercontent.com/1199238/196547161-16f0f2d7-3808-45d8-9bdf-22bff25915e5.png)

**Comment by ykk648** [comment]
> TreatWarningAsError

thanks a lot
