### ISSUE TITLE
Driver not working properly

### ISSUE THREAD

**Issue by vietlhicts** [JannesP/AudioMirror#14]
@JannesP Thank you for your sharing.
I built your code, but I got a new error relate to certificate
![image](https://user-images.githubusercontent.com/63274293/197173940-3e6148a1-5aa9-4533-be02-25ab13ded58d.png)

I installed .cer file
![image](https://user-images.githubusercontent.com/63274293/197174229-82a8b1ad-62cd-49f8-918d-ddb36e010695.png)

Can you help me to check it? Thank you!

**Comment by JannesP** [comment]
Hey, kernel drivers need to be signed by Microsoft to work at all. As far as I know there are no certificates you could install to circumvent that. The only way I know of using the unsigned driver is to run windows in test mode: 
[MSDN Kernel Mode Driver Signatures](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/kernel-mode-code-signing-requirements--windows-vista-and-later-#-kernel-mode-code-signing-requirements-during-development-and-test)
[MSDN Windows Testsigning Configuration](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option)

**Comment by vietlhicts** [comment]
Thank you @JannesP,
Let me check it.

**Comment by vietlhicts** [comment]
@JannesP Thank you so much. Now I can install in Debug mode.
Can I ask you 2 questions?
1. When I build Solution in Release mode, I got many errors. Do you know why? How can I fix it?
![image](https://user-images.githubusercontent.com/63274293/197352411-38aaeff6-020b-44a5-be62-24d791583751.png)

2. Do you know: How can I build Solution to .zip folder (include .exe file) that I can download from some where (I don't want submission to Partner Center). It likes [Download and Install VB-CABLE Driver](https://vb-audio.com/Cable/)
The VB-CABLE doesn't require [MSDN Windows Testsigning Configuration](https://learn.microsoft.com/en-us/windows-hardware/drivers/install/the-testsigning-boot-configuration-option) too

**Comment by JannesP** [comment]
First of all: As I state in the readme, I don't recommend giving this to somebody else in complied form at all. This is more of a POC.

1. I vaguely remember having the same problem in release mode but never tried to fix it. Because it wasn't important at that point.
2. Drivers don't have exe files. You need some kind of separate installer that installs the driver. Aside from that you didn't seem to understand that the driver signature is not an option, it's **mandatory** for kernel drivers. VB-Cable also did that or what makes you believe they didn't?
